---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "jenkins"
  namespace: "jenkins"
spec:
  type: "NodePort"
  selector:
    name: "jenkins"
  ports:
    -
      name: "http"
      port: 80
      targetPort: 8080
      protocol: "TCP"
    -
      name: "slave"
      port: 50000
      protocol: "TCP"
