---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "jenkins"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: "/data/kubernetes-jenkins"

---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jenkins"
  namespace: "jenkins"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
